version: '3'
services:
  api_server:
    build: ./wordify/
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - network

  auth_server:
    build: ./authorize/
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - network

  web_server:
    build: ./path_to_web_server_dockerfile_folder
    ports:
      - "80:80"
    networks:
      - network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

networks:
  network:

volumes:
  db_data:
