version: '3'
services:
  api_server:
    build: ./wordify
    environment:
      CATALINA_OPTS: -Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource
      DB_HOST: db
      DB_USER: api
      DB_PASSWORD: api_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - network

  auth_server:
    build: ./authorize
    environment:
      CATALINA_OPTS: -Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource
      DB_HOST: db
      DB_USER: auth
      DB_PASSWORD: auth_password
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

networks:
  network:

volumes:
  db_data: